version: "3.9"
services:
    app:
        image: ghcr.io/${IMAGE_REPO}:${RELEASE_VERSION} 
        restart: always                               
        ports:                                         
            - "8080"                                     
        container_name: ${APP_NAME}_app                
        environment:                                    
            VIRTUAL_HOST: ${HOST_DOMAIN}
            VIRTUAL_PORT: 8080 # New default ASP.NET port -> https://learn.microsoft.com/en-us/dotnet/core/compatibility/containers/8.0/aspnet-port
            LETSENCRYPT_HOST: ${HOST_DOMAIN}           
            LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}    
        volumes:
            - app-mydb:/app/App_Data  

networks:
  default:
    external: true                                     
    name: nginx                                        

volumes:
    app-mydb:                                          
